### ISSUE TITLE
boost_1_57 no longer compiles with CMake 3.6.3155560

### ISSUE THREAD

**Issue by IgorGanapolsky** [android-ndk/ndk#392]
#### Description
My NDK project used to compile fine with previous versions of CMake and NDK.  Now, with the latest CMake, my boost_1_57_0 included library no longer compiles.  I get errors such as:
> Error:(463, 12) error: use of undeclared identifier 'epoll_create1'; did you mean 'epoll_create'?
> Error:(247, 25) error: use of undeclared identifier 'pthread_mutex_timedlock'
> Error:(28, 10) fatal error: 'asm/page.h' file not found

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 15.0.3869609-beta1
* Build system: cmake
* Host OS: Mac
* Compiler: ndk
* ABI: 'armeabi', 'armeabi-v7a'
* STL: n/a
* NDK API level: minSdk=16, targetSdk=25
* Device API level: Nougat

**Comment by DanAlbert** [comment]
Dup of https://github.com/android-ndk/ndk/issues/302
