### ISSUE TITLE
[BUG][r19c][r20][API16] Undefined reference to __vsnprintf_chk when linking against libc.a and libz.a

### ISSUE THREAD

**Issue by tokohone** [android-ndk/ndk#1069]
#### Description

NDK prebuilt libraries libc(.a) and libz(.a) for API level 16 contain undefined references to __vsnprintf_chk.

The method __vsnprintf_chk seems to be defined in Fortify which was not available yet in API level 16 (it was introduced in 17).

This results in undefined reference linker errors:
bionic/libc/include/bits/fortify/stdio.h:70: error: undefined reference to '__vsnprintf_chk'
bionic/libc/include/bits/fortify/stdio.h:43: error: undefined reference to '__vsnprintf_chk'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

This can be easily seen when comparing older NDK and r19c:

NDK r19c:

nm -g android-ndk-r19c/platforms/android-16/arch-arm/usr/lib/libz.a | grep __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk

 nm -g android-ndk-r19c/platforms/android-16/arch-arm/usr/lib/libc.a | grep __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
00000000 T __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk
         U __vsnprintf_chk

NDK r16b:

nm -g ./android-ndk-r16b/platforms/android-16/arch-arm/usr/lib/libc.a | grep __vsnprintf_chk
<none>

nm -g ./android-ndk-r16b/platforms/android-16/arch-x86/usr/lib/libz.a | grep __vsnprintf_chk
<none>

#### Environment Details

* Tested with NDK versions r19c and r20 (MacOS).
* Works the same both with Android Studio Gradle build and with NDK directly.
* Compiler: clang
* ABI: armeabi-v7a
* NDK API level: 16
* Device API level: 16

**Comment by DanAlbert** [comment]
You need to update your NDK to get the fix. You also need to target the latest API level when using libc.a.

**Comment by DanAlbert** [comment]
Ah, I read that backward, so ignore the first part. You just need to target a newer API level when using libc.a.

**Comment by tokohone** [comment]
Yes, targeting a newer API level (like 17) helps. But that's exactly the point - targeting API level 16 for native code does not work with NDK r19c.

Remember that when compiling for Android with NDK you need to set the target API level to the _minimum_ supported API level.
So I we want to support also API level 16 (Android 4.1) devices, the target API level needs to be set to 16.

See e.g.:
https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md

**Comment by DanAlbert** [comment]
You also can't use libc.a in a library that you load in an app.

That piece of advice is not relevant for libc.a. That advice is there because if you're using libc.so you're linking against a stub library that will not match what is actually on the device. If you link against a stub that's newer than the device the build will succeed but the device won't have the symbols to match what was present at build time. If you use libc.a then all those symbols are linked into your binary; it doesn't matter what's on the device because you're not using it.

**Comment by DanAlbert** [comment]
The API level you build for only affects what is visible in the headers when you're using libc.a. There is (and has always been) only one libc.a for a single API level per ABI. In older NDKs there were dozens of copies, but they were all identical and were libc.a from somewhere between gingerbread and jelly bean. You now have a new libc.a, but you need to use the appropriate headers to match.

**Comment by DanAlbert** [comment]
This is documented in the changelog that first updated them (they're now updated every time we update the headers or stubs): https://github.com/android-ndk/ndk/wiki/Changelog-r17

> Prior NDKs could not use the static libraries with a modern NDK API level because of symbol collisions between libc.a and libandroid_support. This has been solved by removing libandroid_support for modern API levels. A side effect of this is that you must now target at least android-21 to use the static libraries, but these binaries will still work on older devices.

It should perhaps be documented elsewhere as well, but since libc.a is of such limited use I'm not sure where to put that that wouldn't lead people down the wrong path.

**Comment by tokohone** [comment]
Well the fact is that when I updated from NDK r16b to r19c I started getting these missing symbol errors:
bionic/libc/include/bits/fortify/stdio.h:70: error: undefined reference to '__vsnprintf_chk'
bionic/libc/include/bits/fortify/stdio.h:43: error: undefined reference to '__vsnprintf_chk'

I thought it was due to these libz.a and libc.a references. I guess its something else then.
Any ideas why upgrading NDK causes these linker errors?

**Comment by DanAlbert** [comment]
Do you see them if you fix the API level you're building against? If so, then we need more info (the bug template asked for a repro case for the build failure). We have tests that use libc.a without any problem, but dead code elimination could be making it so we don't see whatever is causing the problem.

The undefined references to that symbol in libc.a are expected. There's also one *non*-undefined reference, and that's the one that matters. The rest are just uses of that symbol.

**Comment by tokohone** [comment]
What do you mean "API level you're building against"?

I use the default API level selection so that Gradle configures NDK to use API level 16:
minSdkVersion=16
targetSdkVersion=28
compileSdkVersion=28

This should set ANDROID_PLATFORM=16 automatically:
https://developer.android.com/ndk/guides/cmake#android_platform

I have not yet been able to reproduce this with a simple-enough test app but lets see.

**Comment by DanAlbert** [comment]
Native code is built against `minSdkVersion`. Even though you can use static executables on any version of Android (more or less), it's not possible to configure a single build to use both the API 16 configuration and the API 29 configuration (required for using libc.a) in the same build. Static binaries need to be built separately in a `minSdkVersion 29` project.

**Comment by lbtrace** [comment]
> What do you mean "API level you're building against"?
> 
> I use the default API level selection so that Gradle configures NDK to use API level 16:
> minSdkVersion=16
> targetSdkVersion=28
> compileSdkVersion=28
> 
> This should set ANDROID_PLATFORM=16 automatically:
> https://developer.android.com/ndk/guides/cmake#android_platform
> 
> I have not yet been able to reproduce this with a simple-enough test app but lets see.

Maybe you can replace libz.a of NDK r20 platform 16 with NDK 16 platform 16; or using libz.so
