### ISSUE TITLE
prebuilt gcc doesn't handle atomic_int

### ISSUE THREAD

**Issue by bolds07** [android-ndk/ndk#713]
#### Description

I'm using ndk 17 downloaded from https://dl.google.com/android/repository/android-ndk-r17-linux-x86_64.zip and it seams to not be able to handle atomic_int structures even in very simple cases:

this sample of code:

```
#include <stdatomic.h>

int main()
{
    atomic_int a;
    a = 0;
    
    return 0;
}
```

It compiles and run fine on gcc 5.0
but it doens't compile on arm-linux-androideabi-gcc throwing the error:
` incompatible types when assigning to type 'atomic_int' from type 'int'`

other scenarios show a complete lack of atomic_int support
```
#include <stdatomic.h>

int main()
{
    atomic_int a;
    atomic_int b;
     atomic_int c;
 c = a + b;
    return 0;
}
```
` invalid operands to binary + (have 'atomic_int' and 'atomic_int')`

although the above code makes no sense, since i didn't initialize the variables it is in accord to C standards and compiles fine on gcc 5.0

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: Value from Pkg.Revision in ndk-bundle/source.properties. If not
  the latest version, check there before filing.
* Build sytem: direct compile
* Host OS: Windows, Mac, or Linux? Which Linux? ubuntu 16.04

**Comment by bolds07** [comment]
so good excuse to have something that doesn't work

**Comment by DanAlbert** [comment]
Use clang.

**Comment by enh** [comment]
(to be clear, GCC has been removed in r18. it's only present in r17 to folks one last release to switch to clang.)
