### ISSUE TITLE
compilation error in android-ndk-r19c

### ISSUE THREAD

**Issue by Miteshmakwana73** [android-ndk/ndk#973]
I am getting this error while running the android studio project, gradle is working okay 

```
ui_openssl.c:(.text+0x68): undefined reference to `stdin'
ui_openssl.c:(.text+0x6c): undefined reference to `stdin'
ui_openssl.c:(.text+0x9c): undefined reference to `stderr'
ui_openssl.c:(.text+0xa0): undefined reference to `stderr'
/home/jenya1/Downloads/baresip-studio-master/app/src/main/cpp/../../../../distribution/openssl/lib/arm64-v8a/libcrypto.a(libcrypto-lib-ui_openssl.o): In function `close_console':
ui_openssl.c:(.text+0x374): undefined reference to `stdin'
ui_openssl.c:(.text+0x378): undefined reference to `stdin'
ui_openssl.c:(.text+0x3a0): undefined reference to `stderr'
ui_openssl.c:(.text+0x3a4): undefined reference to `stderr'

```

full Log error
[error.txt](https://github.com/juha-h/baresip-studio/files/3126255/error.txt)

**Comment by enh** [comment]
`stdin`/`stdout`/`stderr` weren't added as variables until API 23. `fread_unlocked`/`fwrite_unlocked` until 28.

you're building this code for API 21 (`--target=aarch64-none-linux-android21`), but it looks like you've built `libcrypto.a` and `libbaresip.a` for a later API level.

**Comment by Miteshmakwana73** [comment]
after updating minsdk 23 it worked

but getting a new error
[new error.txt](https://github.com/android-ndk/ndk/files/3133802/new.error.txt)

**Comment by enh** [comment]
nope, that's the error i mentioned in the second sentence of my original reply. that library was built with target API 28, like i said.

**Comment by Miteshmakwana73** [comment]
so I have to set API_LEVEL=23 ?

**Comment by enh** [comment]
if you want to *run* on API level 23, yes, you need to *build* for API level 23. otherwise the compiler thinks it can use things that weren't available until 24/25/26/27/28, and your code won't run on 23 or earlier.

**Comment by ericQiang** [comment]
> this is my make file
> 
> ```
> # -------------------- VALUES TO CONFIGURE --------------------
> 
> # Path to your Android NDK (must be r19 or higher)
> NDK_PATH  :=  /usr/local/android-ndk-r19
> 
> # Android API level
> API_LEVEL := 28
> 
> # Set default from following values: [armeabi-v7a, arm64-v8a]
> ANDROID_TARGET_ARCH := armeabi-v7a
> 
> # Directory where libraries and include files are instelled
> OUTPUT_DIR := /usr/src/baresip-studio/distribution
> ```
> 
> so I have to set API_LEVEL=23 ?

@Miteshmakwana73 
Hi, have you resolved ?
now ,i get the error 

> jni/../../../src/util_ini.cpp:208: error: undefined reference to 'fread_unlocked'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libmtn_test.so] Error 1

I want compile a apk that run in a embedded device which have android8.1.
 i known that android8.1 corresponding to the api level 27. 

like  @enh said. the function fread_unlocked supported by api 28 or later.
that means i can only compile with sdk-27(because the android 8.1 just support api level 27), but the sdk 27 cannot support 'fread_unlocked'. 

what should i do?

ps. i develop with qt for android. and android-ndk-r19c.
![微信截图_20190712151940](https://user-images.githubusercontent.com/11959271/61109868-914a1580-a4b8-11e9-9ee9-fa1b95cf1232.png)
![微信截图_20190712151931](https://user-images.githubusercontent.com/11959271/61109877-94450600-a4b8-11e9-840c-628eac77da4f.png)

![微信截图_20190712151151](https://user-images.githubusercontent.com/11959271/61109467-8773e280-a4b7-11e9-93b1-c647b6b2a633.png)
i choose android-27  android-28  and android-29， all throw the same error 

> jni/../../../src/util_ini.cpp:208: error: undefined reference to 'fread_unlocked'

best regards.

**Comment by DanAlbert** [comment]
What are you using to build?

**Comment by ericQiang** [comment]
@DanAlbert 
Thanks for your reply.

My environment is: Qt13.0 + jdk1.8.0_181 + android-sdk(27,28,29) + android-ndk-r19c. suck as the following picture show.
![微信截图_20190712170401](https://user-images.githubusercontent.com/11959271/61116461-13d9d180-a4c7-11e9-895a-1effeed6afce.png)

the following files come from my test project. can you point out what's my fault?
thanks.
the following files with a .txt suffix for uploading.
[gradle-wrapper.properties.txt](https://github.com/android-ndk/ndk/files/3385751/gradle-wrapper.properties.txt)
[gradlew.bat.txt](https://github.com/android-ndk/ndk/files/3385760/gradlew.bat.txt)
[gradlew.txt](https://github.com/android-ndk/ndk/files/3385761/gradlew.txt)
[AndroidManifest.xml.txt](https://github.com/android-ndk/ndk/files/3385762/AndroidManifest.xml.txt)
[build.gradle.txt](https://github.com/android-ndk/ndk/files/3385763/build.gradle.txt)
[mtn_test.pro.txt](https://github.com/android-ndk/ndk/files/3385766/mtn_test.pro.txt)
[Makefile.txt](https://github.com/android-ndk/ndk/files/3385768/Makefile.txt)

**Comment by ericQiang** [comment]
oh, @DanAlbert I found the reason.
in the makefile 

> LFLAGS        = --sysroot=C:\Android\android-ndk-r19c/platforms/android-21/...
I changed the platform in the gui interface of QT. but that not take effect. I changed the android-21 to android-28 manually, and it worked.

But unfortunately, the apk cannot run on my device. because my device is android 8.1(api level27).

So, if or not i compile a standalone "fread_unlocked" and linked into my project?
or how should we do when we use "fread_unlocked" in project with api level older 28,?

Thanks

**Comment by enh** [comment]
if you just replace `fread_unlocked` with `fread`, you'll have code that works on older devices. it'll be slightly slower because it'll do the extra locking, but that's unavoidable on older devices.

**Comment by ericQiang** [comment]
> if you just replace `fread_unlocked` with `fread`, you'll have code that works on older devices. it'll be slightly slower because it'll do the extra locking, but that's unavoidable on older devices.

@enh 
Thanks for your reply. 
now it seems that i have to use your method.

regards

**Comment by linuxaged** [comment]
> `stdin`/`stdout`/`stderr` weren't added as variables until API 23. `fread_unlocked`/`fwrite_unlocked` until 28.

why ndk try to link `fread_unlocked`/`fwrite_unlocked` when i use `std::fwrite`?

**Comment by enh-google** [comment]
> why ndk try to link fread_unlocked/fwrite_unlocked when i use std::fwrite?

it doesn't. you're using fread_unlocked/fwrite_unlocked somewhere. you can find out where by using objdump on your .o/.so files.

**Comment by amir28** [comment]
I had this issue in compiling linux kernel for android 10(api 29).
```
drivers/built-in.o: In function `_save_testing_data':
/mnt/Android/Phone/oneplus-nord-n10/bd/downloads/sdm630-kernel/drivers/input/touchscreen/gt1x/test_function.c:1065: undefined reference to `fwrite_unlocked'
/mnt/Android/Phone/oneplus-nord-n10/bd/downloads/sdm630-kernel/drivers/input/touchscreen/gt1x/test_function.c:1087: undefined reference to `fwrite_unlocked'
/mnt/Android/Phone/oneplus-nord-n10/bd/downloads/sdm630-kernel/drivers/input/touchscreen/gt1x/test_function.c:939: undefined reference to `fwrite_unlocked'
/mnt/Android/Phone/oneplus-nord-n10/bd/downloads/sdm630-kernel/drivers/input/touchscreen/gt1x/test_function.c:953: undefined reference to `fwrite_unlocked'
/mnt/Android/Phone/oneplus-nord-n10/bd/downloads/sdm630-kernel/drivers/input/touchscreen/gt1x/test_function.c:1104: undefined reference to `fwrite_unlocked'
drivers/built-in.o:/mnt/Android/kernel/drivers/input/touchscreen/gt1x/test_function.c:1112: more undefined references to `fwrite_unlocked' follow
make[1]: *** [/mnt/Android/linuxkernel/Makefile:1001: vmlinux] Error 1
```
adding this in Makefile solved it.
```
subdir-ccflags-y += \
        -fno-builtin-fwrite \
        -Wno-sizeof-pointer-div
```

**Comment by enh-google** [comment]
@amir28 --- can you file a new bug for that? i think that's an unrelated issue that i'm not sure we've checked (if clang is automatically "optimizing" fwrite() to fwrite_unlocked() without paying attention to API level).

**Comment by rprichard** [comment]
They're compiling a kernel, so AFAIK there shouldn't be an Android API level. sdm630 has been around a while -- is @amir28 using gcc or clang to build it?

I think the existence of `fflush(nullptr)` would make an `fwrite` -> `fwrite_unlocked` optimization impractical in general.

I'd guess that a header is defining `fwrite` to `fwrite_unlocked`, but then I don't know why `-fno-builtin-fwrite` would fix it.

**Comment by DanAlbert** [comment]
The bug originally reported here was user error. If you think you've found a bug, please file a new one (we need the information asked for in the template). Locking to encourage that.
