### ISSUE TITLE
[BUG] r20 Build fails with custom clang

### ISSUE THREAD

**Issue by AmitKaushikGIT** [android-ndk/ndk#1006]
#### Description
Building with custom clang - based on llvm-project version 5
It was working perfectly with ndk-r16b, cmake 3.6
changes in ndk toolchain file
set(ANDROID_C_COMPILER
  "${ANDROID_TOOLCHAIN_ROOT}/bin/clang${ANDROID_TOOLCHAIN_SUFFIX}")
set(ANDROID_CXX_COMPILER
  "${ANDROID_TOOLCHAIN_ROOT}/bin/clang++${ANDROID_TOOLCHAIN_SUFFIX}")
set(ANDROID_ASM_COMPILER
  "${ANDROID_TOOLCHAIN_ROOT}/bin/clang${ANDROID_TOOLCHAIN_SUFFIX}")
if (ANDROID_TOOLCHAIN STREQUAL myclang)
  if (UNIX AND NOT APPLE)
    # for Linux, BSD, Solaris, Minix
    set(ABC "${CLANG_DIR}/llvm-build/Linux/bin/")
  elseif (APPLE)
    # for Mac OS
    set(ABC "${CLANG_DIR}/llvm-build//MacOS/bin/")
  endif ()
  set(ANDROID_C_COMPILER "${ABC}clang${ANDROID_TOOLCHAIN_SUFFIX}")
  set(ANDROID_CXX_COMPILER "${ABC}clang++${ANDROID_TOOLCHAIN_SUFFIX}")
  set(ANDROID_ASM_COMPILER "${ABC}clang${ANDROID_TOOLCHAIN_SUFFIX}")
endif ()

Following error occurs:

error: cannot find -lm
error: cannot find -lcompiler_rt-extras
error: cannot find -ldl
error: cannot find -lc
error: cannot find -lcompiler_rt-extras
error: cannot find -ldl

Note: there was another error, 
 clang: error: unknown argument: '-fno-addrsig'
Solved it by commenting below code from toolchain file
#list(APPEND ANDROID_COMPILER_FLAGS -fno-addrsig)

* NDK Version:  20.0.5594570

* Build system:  CMake, version 3.10 and 3.6
* Host OS:  Mac
* ABI: x86
* minsdk 16

**Comment by enh** [comment]
probably need to read https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md --- it certainly mentions `-fno-addrsig`.

**Comment by AmitKaushikGIT** [comment]
@enh thanks for link, but my clang does not recognise the flag

**Comment by DanAlbert** [comment]
Then your custom Clang is too old to work with the NDK.

**Comment by AmitKaushikGIT** [comment]
I have mentioned the clang if built by forking llvm-project version 5, is there any documentation for which versions are supported. Also please address the other issues
rror: cannot find -lm
error: cannot find -lcompiler_rt-extras
error: cannot find -ldl
error: cannot find -lc
error: cannot find -lcompiler_rt-extras
error: cannot find -ldl

**Comment by AmitKaushikGIT** [comment]
list(APPEND CMAKE_SYSTEM_LIBRARY_PATH
  "${CMAKE_SYSROOT}/usr/lib/${ANDROID_TOOLCHAIN_NAME}/${ANDROID_PLATFORM_LEVEL}")
cause CMAKE_SYSTEM_LIBRARY_PATH=/usr/lib/${ANDROID_TOOLCHAIN_NAME}/${ANDROID_PLATFORM_LEVEL}

I tried changing to list(APPEND CMAKE_SYSTEM_LIBRARY_PATH
  "${CMAKE_SYSROOT}/usr/lib/${ANDROID_TOOLCHAIN_NAME}/${ANDROID_PLATFORM_LEVEL}")

Still I get the above errors. I am clueless on this. Please help resolve.

**Comment by DanAlbert** [comment]
The SVN revision of our clang is noted in the change log for the release. You'll need to update to that.

**Comment by AmitKaushikGIT** [comment]
this looks like linker is not able to find libraries listed. It could be path problem.

**Comment by stephenhines** [comment]
As Dan mentioned, we really don't support alternate compilers as part of the NDK. It ships with a toolchain that has been validated to work with the headers, libraries, and build configurations of the NDK. Trying to make the NDK work for a variety of external compilers is not something that we can easily do, as part of switching to a reasonably close to top-of-tree Clang was to reduce the overall maintenance burden.

**Comment by enh** [comment]
in particular: the current clang has a lot of Android-specific knowledge in the compiler driver so that build systems _don't_ need to know as much about Android as they used to. at the very least you'll need those changes.

**Comment by AmitKaushikGIT** [comment]
> in particular: the current clang has a lot of Android-specific knowledge in the compiler driver so that build systems _don't_ need to know as much about Android as they used to. at the very least you'll need those changes.

@enh how can I build clang with those changes?

**Comment by AmitKaushikGIT** [comment]
My use case is I have custom transformer for obfuscation of global strings. Which I believe is not possible with ndk's clang. There can be lot of such use cases for other users. I am not sure what factors are driving for making clang aware of ndk and android related stuff.

**Comment by cw8783** [comment]
cw

**Comment by stephenhines** [comment]
> > in particular: the current clang has a lot of Android-specific knowledge in the compiler driver so that build systems _don't_ need to know as much about Android as they used to. at the very least you'll need those changes.
> 
> @enh how can I build clang with those changes?

You should rebase your Clang to a more recent version or consider rewriting your tool as a [Clang plugin](https://clang.llvm.org/docs/ClangPlugins.html) against the exported version of the NDK's Clang. We share all of our sources and work on this right [here](https://android.googlesource.com/toolchain/llvm_android/).

> I am not sure what factors are driving for making clang aware of ndk and android related stuff.

Can you explain what you mean by this? Several folks in Android work directly on Clang/LLVM, and the rest of the community is very aware of Android's needs/uses.

**Comment by AmitKaushikGIT** [comment]
Hi @stephenhines, I don't have expertise in this area so please pardon anything novice, I will put my concerns and questions, please take some time to address them:
1. I have been using this project for doing string obfuscation in my ndk project `https://github.com/heroims/obfuscator/tree/llvm-8.0/lib/Transforms/Obfuscation`. It worked fine with clang 5.0.0 and ndk-16. When I upgrade to ndk20. Clang starts breaking with above mentioned errors.
2. As advised I tried to upgrade clang to latest stable version 7.0.0. Which is resulting in following errors. 

> File 'string' not found
Solved this using include path `-I/Users/amit.kaushik/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/`

Then linker error popped up `error: undefined reference to 'std::__ndk1::recursive_mutex::lock()`

3. I think(I am not sure) ndk clang is aware of include paths and library paths. Which I feel should not be there. Reason for this thinking is my custom clang was able to build with ndk 16 flawlessly but not with ndk 20.

4. Is it possible to put such functionality(``https://github.com/heroims/obfuscator/tree/llvm-8.0/lib/Transforms/Obfuscation``) in clang plugin

Thanks

**Comment by AmitKaushikGIT** [comment]
Hi I am able to make it work with following changes to ndk's android.toolchain..cmake

```
set(ANDROID_CXX_STANDARD_LIBRARIES)
foreach(library ${ANDROID_STL_STATIC_LIBRARIES})
	list(APPEND ANDROID_CXX_STANDARD_LIBRARIES
		"${ANDROID_NDK}/sources/cxx-stl/${ANDROID_STL_PREFIX}/libs/${ANDROID_ABI}/lib${library}.a.${MIN_API}")
endforeach()
foreach(library ${ANDROID_STL_SHARED_LIBRARIES})
	list(APPEND ANDROID_CXX_STANDARD_LIBRARIES
		"${ANDROID_NDK}/sources/cxx-stl/${ANDROID_STL_PREFIX}/libs/${ANDROID_ABI}/lib${library}.so.${MIN_API}")
endforeach()

```

Because **$ANDROID_NDK/sources/cxx-stl/llvm-libc++/libs/x86/lib** contains api specific so, can you suggest if there are any implication for this.

**Comment by DanAlbert** [comment]
No stable version of Clang has all the patches you need. You need to update to the same revision we're using.
